"""Draws the app icon (a magnifier over a disk-usage ring) with the standard library only.
Writes icon.ico (for the .exe) and appicon.py (a small embedded PNG for the window icon).
    python make_icon.py
"""
import base64
import math
import struct
import zlib


def _mix(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def _hex(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


TOP, BOTTOM = _hex('#4a5bd8'), _hex('#1b2766')
SLICES = [(0, 215, _hex('#48d17c')), (215, 305, _hex('#ffc83d')), (305, 360, _hex('#ff6b6b'))]
CX = CY = 0.44
WHITE = (255, 255, 255)


def sample(u, v):
    """Colour and opacity of the icon at (u, v) in the unit square."""
    dx, dy = max(abs(u - 0.5) - 0.27, 0), max(abs(v - 0.5) - 0.27, 0)
    if math.hypot(dx, dy) > 0.2:
        return None                                                   # outside the rounded square
    color = _mix(TOP, BOTTOM, v)
    d = math.hypot(u - CX, v - CY)
    # magnifier handle (a capsule)
    ax, ay, bx, by = CX + 0.245, CY + 0.245, 0.86, 0.86
    t = max(0, min(1, ((u - ax) * (bx - ax) + (v - ay) * (by - ay)) / ((bx - ax) ** 2 + (by - ay) ** 2)))
    if math.hypot(u - (ax + t * (bx - ax)), v - (ay + t * (by - ay))) <= 0.052:
        return WHITE
    if 0.318 <= d <= 0.362:                                           # lens rim
        return WHITE
    if 0.15 <= d <= 0.29:                                             # disk-usage ring
        angle = (math.degrees(math.atan2(v - CY, u - CX)) + 90) % 360
        for lo, hi, col in SLICES:
            if lo + 1.5 <= angle < hi - 1.5:
                return col
        return color
    if d < 0.318:
        return _mix(color, WHITE, 0.07)                               # faint glass tint
    return color


def render(size, ss=4):
    rows = []
    for y in range(size):
        row = bytearray()
        for x in range(size):
            r = g = b = a = 0.0
            for sy in range(ss):
                for sx in range(ss):
                    px = sample((x + (sx + 0.5) / ss) / size, (y + (sy + 0.5) / ss) / size)
                    if px is not None:
                        r, g, b, a = r + px[0], g + px[1], b + px[2], a + 1
            n = ss * ss
            if a:
                row += bytes((round(r / a), round(g / a), round(b / a), round(255 * a / n)))
            else:
                row += b'\0\0\0\0'
        rows.append(bytes(row))
    return rows


def png(size):
    raw = b''.join(b'\0' + row for row in render(size, 4 if size <= 128 else 3))

    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)

    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def main():
    sizes = [16, 24, 32, 48, 64, 128, 256]
    images = {s: png(s) for s in sizes}
    header = struct.pack('<HHH', 0, 1, len(sizes))
    offset = 6 + 16 * len(sizes)
    entries = b''
    for s in sizes:
        entries += struct.pack('<BBBBHHII', s % 256, s % 256, 0, 0, 1, 32, len(images[s]), offset)
        offset += len(images[s])
    with open('icon.ico', 'wb') as fh:
        fh.write(header + entries + b''.join(images[s] for s in sizes))
    with open('appicon.py', 'w') as fh:
        fh.write('"""Generated by make_icon.py - the window icon as a base64 PNG."""\n')
        fh.write('ICON_PNG_B64 = (\n')
        b64 = base64.b64encode(images[64]).decode()
        for i in range(0, len(b64), 100):
            fh.write(f"    '{b64[i:i + 100]}'\n")
        fh.write(')\n')
    with open('icon_preview.png', 'wb') as fh:
        fh.write(images[256])
    print('wrote icon.ico, appicon.py, icon_preview.png')


if __name__ == '__main__':
    main()
